# Generated by Django 4.1.2 on 2022-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(max_length=1000),
        ),
    ]
