# Generated by Django 4.1.2 on 2022-12-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsarticle_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLabel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticleNewsLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle')),
                ('news_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newslabel')),
            ],
        ),
    ]
