# Generated by Django 4.1.2 on 2022-12-05 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_newsarticlenewslabel_news_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticlenewslabel',
            name='news_article',
        ),
        migrations.RemoveField(
            model_name='newsarticlenewslabel',
            name='news_label',
        ),
        migrations.AddField(
            model_name='newsarticlenewslabel',
            name='news_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsarticlenewslabel',
            name='news_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newslabel'),
            preserve_default=False,
        ),
    ]
