# Generated by Django 4.1.2 on 2022-12-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_newsarticlenewslabel_news_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='autocratic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='bias',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='conservative',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='liberal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='socialist',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
