# Generated by Django 4.1.2 on 2022-12-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsarticle_autocratic_newsarticle_bias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='bias',
        ),
    ]
